#ifndef GEOTAB_CRYPTO_ERRORS_H
#define GEOTAB_CRYPTO_ERRORS_H

#define GEOTAB_CRYPTO_SUCCESS 0
#define GEOTAB_CRYPTO_ERROR_INVALID_ARGS -1
#define GEOTAB_CRYPTO_ERROR_MEMORY_ALLOC -2


#endif // GEOTAB_CRYPTO_ERRORS_H